name: CI

on:
    push:
        branches:
            - master
    pull_request:
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                os: [ubuntu-latest]
                node_version: [16]
                include:
                    - os: macos-latest
                      node_version: 16
                    - os: windows-latest
                      node_version: 16
            fail-fast: false

        name: 'Build: node-${{ matrix.node_version }}, ${{ matrix.os }}'
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PNPM
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node_version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Build bundle
              run: pnpm run build

    ESLint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node_version: [16]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PNPM
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node_version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: ESLint
              run: pnpm exec eslint ./src

    Test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                os: [ubuntu-latest]
                node_version: [16]
                include:
                    - os: macos-latest
                      node_version: 16
                    - os: windows-latest
                      node_version: 16
            fail-fast: false

        name: 'Test: node-${{ matrix.node_version }}, ${{ matrix.os }}'
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PNPM
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node_version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Test with coverage
              run: pnpm test:cov

            - name: Code coverage
              uses: codecov/codecov-action@v2
              with:
                  token: ${{secrets.CODECOV_TOKEN}}
                  fail_ci_if_error: true
                  verbose: true
